#!/bin/sh

. /etc/profile

URL="http://admin@localhost/rest/apps"
PKG="50_havis.device.io-api.jar 50_@Bundle-SymbolicName@.jar 50_havis.net.rest.io.jar"

for pkg in $PKG; do
  busybox wget $URL/$pkg/plug -q --spider
done

exit 0